<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon CRUD</title>
        <link rel="stylesheet" href="<?php echo $this->url->get('public\css\bootstrap.min.css')?>"/>
        <link rel="stylesheet" href="<?php echo $this->url->get('public\css\navbar-fixed-top.css')?>"/>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
      <nav class="navbar navbar-inverse navbar-fixed-top" >
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="#">CRUD</a>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="navbarCollapse">
                  <ul class="nav navbar-nav">
                      <li><a href="<?php echo $this->url->get('home')?>">Home</a></li>
                      <li><a href="<?php echo $this->url->get('users')?>" >User</a></li>

                  </ul>
              </div>
          </div>
      </nav>

        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>
